version: "3"

volumes:
  pgdata:
services:
  web: &python
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/code
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - rabbitmq
      - celery_beat
      - celery_worker
#baza danych
  postgres:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

#broker dla celery
  rabbitmq:
    image: rabbitmq:3.7-alpine


#celery_beat
  celery_beat:
    <<: *python
    environment:
      - C_FORCE_ROOT=true
    # test czy działa, normalnie przenieść tutaj celery -A teoproject worker -l info -B, ewentualnie z -Q i queusami.
    #command: bash -c "celery -A teoproject worker -l info -Q default,high_priority,low_priority -c5 -B"
    command: bash -c "celery -A teoproject worker -l info -Q default,high_priority,low_priority -c5 -B"
    ports: []
    depends_on:
      - postgres
      - rabbitmq

#celery_worker
  celery_worker:
    <<: *python
    #environment:
      #- C_FORCE_ROOT=true
    command: bash -c "celery -A teoproject worker -l info"
    ports: []
    depends_on:
      - postgres
      - rabbitmq