version: "3"

volumes:
  pgdata:
services:
  web: &python
    build: .

    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8080"

    volumes:
      - .:/code
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - rabbitmq
      - celery_worker
#baza danych
  postgres:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

#broker dla celery
  rabbitmq:
    image: rabbitmq:3.7-alpine

#celery
  celery_worker:
    <<: *python
    # test czy działa, normalnie przenieść tutaj celery -A teoproject worker -l info -B, ewentualnie z -Q i queusami.
    command: bash -c "python manage.py makemigrations"
    ports: []
    depends_on:
      - postgres
      - rabbitmq

