# Generated by Django 2.2.1 on 2019-05-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_postTitle', models.CharField(max_length=120)),
                ('postURL', models.TextField()),
                ('postContent', models.TextField()),
                ('postAuthor', models.CharField(max_length=120)),
                ('postDate', models.CharField(max_length=120)),
            ],
        ),
    ]
