# Generated by Django 2.2.1 on 2019-05-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teoapp', '0004_postauthor_postcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='postauthor',
            name='posts',
            field=models.TextField(blank=True),
        ),
    ]
