# Generated by Django 2.2.1 on 2019-05-18 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teoapp', '0005_postauthor_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcontent',
            name='author',
        ),
        migrations.RemoveField(
            model_name='postcontent',
            name='title',
        ),
    ]
