# Generated by Django 2.2.1 on 2019-05-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teoapp', '0006_auto_20190518_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontent',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
