# Generated by Django 2.2.1 on 2019-05-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teoapp', '0007_auto_20190518_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcontent',
            name='content',
        ),
    ]
