# Generated by Django 2.2.1 on 2019-05-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teoapp', '0008_remove_postcontent_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcontent',
            name='_content',
            field=models.TextField(blank=True),
        ),
    ]
