# Generated by Django 2.2.1 on 2019-05-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teoapp', '0010_auto_20190518_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='postauthor',
            name='topTen',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='postcontent',
            name='_content',
            field=models.TextField(blank=True),
        ),
    ]
