# Generated by Django 2.2.1 on 2019-05-18 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teoapp', '0011_auto_20190518_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postauthor',
            old_name='topTen',
            new_name='_topTen',
        ),
    ]
