# Generated by Django 2.2.1 on 2019-05-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teoapp', '0012_auto_20190518_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcontent',
            name='_topTen',
            field=models.TextField(blank=True),
        ),
    ]
