# Generated by Django 2.2.1 on 2019-05-21 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teoapp', '0013_postcontent__topten'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postauthor',
            options={'ordering': ('name',)},
        ),
    ]
