# Generated by Django 2.2.1 on 2019-05-21 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teoapp', '0014_auto_20190521_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postauthor',
            options={},
        ),
    ]
